events {}events {}
http {
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/localhost+2.pem;
        ssl_certificate_key /etc/nginx/certs/localhost+2-key.pem;

        location /users {
            proxy_pass http://backend:8000;
        }

        location /rooms {
            proxy_pass http://backend:8000;
        }

        location /comments {
            proxy_pass http://backend:8000;
        }

        location /ws {
            proxy_pass http://backend:8000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location / {
            proxy_pass http://frontend:3000;
        }
    }
}
